spring:
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1/ng-db
    username: root
    password: Superadmin123
server:
  servlet:
    context-path: /api
